@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< Updated upstream
<<<<<<< HEAD
REM Generated by Vivado on Thu May 09 08:58:46 -0700 2024
=======
REM Generated by Vivado on Fri May 10 10:44:31 -0700 2024
>>>>>>> ab5ba988deae8f179456a57f52293199af0a5352
=======
REM Generated by Vivado on Fri May 10 17:13:59 -0700 2024
>>>>>>> Stashed changes
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot OTTER_tb_behav xil_defaultlib.OTTER_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot OTTER_tb_behav xil_defaultlib.OTTER_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
