@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu May 09 08:38:22 -0700 2024
=======
REM Generated by Vivado on Fri May 10 10:44:33 -0700 2024
>>>>>>> ab5ba988deae8f179456a57f52293199af0a5352
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim OTTER_tb_behav -key {Behavioral:sim_1:Functional:OTTER_tb} -tclbatch OTTER_tb.tcl -view C:/Users/Ray/CalPoly/2023/CPE333/PipelinedOtter/OTTER_tb_behav.wcfg -log simulate.log"
call xsim  OTTER_tb_behav -key {Behavioral:sim_1:Functional:OTTER_tb} -tclbatch OTTER_tb.tcl -view C:/Users/Ray/CalPoly/2023/CPE333/PipelinedOtter/OTTER_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
